spring:
  #datasource
  datasource:
    username: leibees
    password: leibees
    url: jdbc:mysql://120.27.24.193:3306/edu-device-manage?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: edu-device-manage
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  # view
  freemarker:
    prefix:
    suffix: .ftl
    template-loader-path: ["classpath:/templates/"]
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  resources:
    static-locations: ["file:${upload.path}","classpath:/static/"]
server:
  port: 80


#log
logging:
  config: classpath:logback-spring.xml

# mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# mapper
mapper:
  enum-as-simple-type: true

upload:
  path: D:\Project-Upload

## 自定义配置
fast:
  generate:
    package:
      parent: edu.device.manage
    strategy:
      sync: entity_to_database
    global:
      generatorFile: false
      enable: true
    dataSource:
      delOverColumn: true
